services:
  db:
    image: mysql:8.0
    container_name: memory_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
    user: "999:999" 
    ports:
      - "3306:3306"
    networks:
      - my_network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  backend:
    build: ./backend
    container_name: memory_backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - ./backend/static:/app/static
      - ./backend/media:/app/media
    ports:
      - "8001:8001"
    env_file:
      - .env  
    depends_on:
      - db
    networks:
      - my_network
    restart: always

  nginx:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    restart: always
    container_name: memory_frontend_nginx
    ports:
      - "3000:3000"    # HTTP
#      - "443:443"  # HTTPS
    volumes:
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
#      - /etc/letsencrypt:/etc/letsencrypt:ro  # Certificados SSL
    networks:
      - my_network
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${VITE_API_URL}


volumes:
  db_data:
  static_volume:
  media_volume:

networks:
  my_network:
    driver: bridge


