# Generated by Django 5.2.5 on 2025-08-18 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('capa_img', models.ImageField(upload_to='capas')),
                ('fundo_img', models.ImageField(upload_to='fundos')),
            ],
            options={
                'db_table': 'anime',
            },
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carta_img', models.ImageField(upload_to='cartas')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temas.anime')),
            ],
            options={
                'db_table': 'carta',
            },
        ),
    ]
